In [1]:
# import pandas
import pandas as pd

In [2]:
df= pd.read_csv('pn_data.csv') # load file - import dataframe
df

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000
2    ak   28           40000
3    vj   19           50000
4    av    4             555
5    rj    3             777

In [101]:
# 4 Rows & Columns - Selection

In [3]:
# select single column
df[['Name']]

   Name
0   ram
1  ravi
2    ak
3    vj
4    av
5    rj

In [4]:
# select multiple columns
df[['Name', 'Monthly_Salary']]

   Name  Monthly_Salary
0   ram           10000
1  ravi            3000
2    ak           40000
3    vj           50000
4    av             555
5    rj             777

In [7]:
# select single row || loc - label based index  // loc rows ko filter/select karta hai.
df.loc[df.Name=='ravi']

   Name  Age  Monthly_Salary
1  ravi   37            3000

In [9]:
# select multiple rows || loc - label based index
df.loc[(df.Name=='ram') & (df.Monthly_Salary>=9000)]

Empty DataFrame
Columns: [Name, Age, Monthly_Salary]
Index: []

In [10]:
df.loc[0:2]

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000
2    ak   28           40000

In [107]:
# Select Rows || iloc - index-value based
# df.iloc[0]
df.iloc[0:2] # [start:stop:step]

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000

In [14]:
df.loc[0:2]  #0 2 include index
df.iloc[0:2]  #[start:stop:step]

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000

In [109]:
# 5 Filter Dataframe - Filtering by column values

In [15]:
df

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000
2    ak   28           40000
3    vj   19           50000
4    av    4             555
5    rj    3             777

In [17]:
df['Age'] >18

0     True
1     True
2     True
3     True
4    False
5    False
Name: Age, dtype: bool

In [20]:
df[df['Age']>=18]

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000
2    ak   28           40000
3    vj   19           50000

In [21]:
df_age_filter = df[df['Age'] >= 18] # filter and store dataframe in a new variable

In [22]:
df_age_filter

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000
2    ak   28           40000
3    vj   19           50000

In [23]:
df[(df['Age'] >= 28) & (df['Monthly_Salary'] >= 3000)] # multiple filter conditions

   Name  Age  Monthly_Salary
1  ravi   37            3000
2    ak   28           40000

In [27]:
df.where(df['Age'] >= 28) # where function replace values in a DataFrame based on a condition
# df[df['Age']>=28]

# Method	क्या करता है
# where()	condition false होने पर NaN डालता है
# loc[]	false rows को हटा देता है

# where() data cleaning और masking में बहुत use होता है।

   Name   Age  Monthly_Salary
0   NaN   NaN             NaN
1  ravi  37.0          3000.0
2    ak  28.0         40000.0
3   NaN   NaN             NaN
4   NaN   NaN             NaN
5   NaN   NaN             NaN

In [119]:
df.where(df['Age'] >= 28, other = 'Not Eligible')

           Name           Age Monthly_Salary
0  Not Eligible  Not Eligible   Not Eligible
1          ravi            37           3000
2            ak            28          40000
3  Not Eligible  Not Eligible   Not Eligible

In [39]:
# 6 Rows and Columns - Operation (Add, update, delete)

In [40]:
df

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000
2    ak   28           40000
3    vj   19           50000

In [41]:
# Create a new column
df['college'] = ['rjit', 'itm', 'mpct', 'mits']
df

   Name  Age  Monthly_Salary college
0   ram   26           10000    rjit
1  ravi   37            3000     itm
2    ak   28           40000    mpct
3    vj   19           50000    mits

In [42]:
# Add new columns using existing column/s
df['Bonus'] = df['Monthly_Salary'] * 0.20
df

   Name  Age  Monthly_Salary college    Bonus
0   ram   26           10000    rjit   2000.0
1  ravi   37            3000     itm    600.0
2    ak   28           40000    mpct   8000.0
3    vj   19           50000    mits  10000.0

In [43]:
# Add new row - at the end of dataframe
df.loc[len(df)] = ['viki', 23, 2000, 'mpct', 1000]
df

   Name  Age  Monthly_Salary college    Bonus
0   ram   26           10000    rjit   2000.0
1  ravi   37            3000     itm    600.0
2    ak   28           40000    mpct   8000.0
3    vj   19           50000    mits  10000.0
4  viki   23            2000    mpct   1000.0

In [44]:
# update value in dataframe using index-name
df.loc[0, 'Monthly_Salary'] = 5000
df

   Name  Age  Monthly_Salary college    Bonus
0   ram   26            5000    rjit   2000.0
1  ravi   37            3000     itm    600.0
2    ak   28           40000    mpct   8000.0
3    vj   19           50000    mits  10000.0
4  viki   23            2000    mpct   1000.0

In [47]:
# update value in dataframe using column-value
df.loc[df.Name=='ram','Monthly_Salary'] = 90000
df

   Name  Age  Monthly_Salary college    Bonus
0   ram   26           90000    rjit   2000.0
1  ravi   37            3000     itm    600.0
2    ak   28           40000    mpct   8000.0
3    vj   19           50000    mits  10000.0
4  viki   23            2000    mpct   1000.0

In [48]:
# delete value - rows and columns

In [49]:
# delete row using column-value filter
df = df.drop(df[df.Name == 'viki'].index) # delete row, axis= 0

In [50]:
# delete row using index-name filter
df.drop(1, axis=0)

  Name  Age  Monthly_Salary college    Bonus
0  ram   26           90000    rjit   2000.0
2   ak   28           40000    mpct   8000.0
3   vj   19           50000    mits  10000.0

In [51]:
df.drop('Bonus', axis=1, inplace=True) # delete one column
# df.drop(['Bonus', 'Team'], axis=1, inplace=True) # delete multiple columns

In [52]:
df

   Name  Age  Monthly_Salary college
0   ram   26           90000    rjit
1  ravi   37            3000     itm
2    ak   28           40000    mpct
3    vj   19           50000    mits

In [53]:
df.rename(columns={'Monthly_Salary': 'Salary'}, inplace=True) # rename column name

In [54]:
df

   Name  Age  Salary college
0   ram   26   90000    rjit
1  ravi   37    3000     itm
2    ak   28   40000    mpct
3    vj   19   50000    mits

In [55]:
# sort values - order values in dataframe by asc or desc order
df.sort_values('Salary') #ascending order, by default

   Name  Age  Salary college
1  ravi   37    3000     itm
2    ak   28   40000    mpct
3    vj   19   50000    mits
0   ram   26   90000    rjit

In [56]:
# sort values in descending order
df.sort_values('Salary', ascending=False)

   Name  Age  Salary college
0   ram   26   90000    rjit
3    vj   19   50000    mits
2    ak   28   40000    mpct
1  ravi   37    3000     itm

In [57]:
# 7 working with date value

In [58]:
# create a date column - date of joining
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03']
df

   Name  Age  Salary college         DOJ
0   ram   26   90000    rjit  2024-01-01
1  ravi   37    3000     itm  2024-01-15
2    ak   28   40000    mpct  2024-03-28
3    vj   19   50000    mits  2024-03-03

In [61]:
df['DOJ'].dtype # object-type value
# dtype('O')

In [62]:
df['DOJ'] = pd.to_datetime(df['DOJ']) # change to date-time type

In [63]:
df['DOJ'].dtype # date-time type

dtype('<M8[us]')

In [64]:
df1 = df

In [65]:
# creating a new column with incorrect date format
df1['DOJ2'] = ['01-01-2025', '15-01-2025', '28-03-2025', '03-03-2025']
df1

   Name  Age  Salary college        DOJ        DOJ2
0   ram   26   90000    rjit 2024-01-01  01-01-2025
1  ravi   37    3000     itm 2024-01-15  15-01-2025
2    ak   28   40000    mpct 2024-03-28  28-03-2025
3    vj   19   50000    mits 2024-03-03  03-03-2025

In [67]:
df1['DOJ2'].dtype  # object-type value

In [68]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'], format = '%d-%m-%Y') # change to date-time type using date-format

In [69]:
df1['DOJ2'].dtype

dtype('<M8[us]')

In [70]:
df = df.drop('DOJ2', axis=1)
df

   Name  Age  Salary college        DOJ
0   ram   26   90000    rjit 2024-01-01
1  ravi   37    3000     itm 2024-01-15
2    ak   28   40000    mpct 2024-03-28
3    vj   19   50000    mits 2024-03-03

In [71]:
# extract year, month, week, day
df['DOJ'].dt.year
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0      Monday
1      Monday
2    Thursday
3      Sunday
Name: DOJ, dtype: str

In [72]:
# create new column using month extract function from DOJ column
df['Month'] = df['DOJ'].dt.month

In [73]:
df

   Name  Age  Salary college        DOJ  Month
0   ram   26   90000    rjit 2024-01-01      1
1  ravi   37    3000     itm 2024-01-15      1
2    ak   28   40000    mpct 2024-03-28      3
3    vj   19   50000    mits 2024-03-03      3

In [74]:
df['DOJ'] + pd.Timedelta(days=90) # add 90 days to DOJ column

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
Name: DOJ, dtype: datetime64[us]

In [ ]:
# 8 Handling Missing Values