In [1]:
# import pandas
import pandas as pd

In [2]:
df= pd.read_csv('pn_data.csv') # load file - import dataframe
df

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000
2    ak   28           40000
3    vj   19           50000
4    av    4             555
5    rj    3             777

In [3]:



# 4 Rows & Columns - Selection

In [4]:
# select single column
df[['Name']]

   Name
0   ram
1  ravi
2    ak
3    vj
4    av
5    rj

In [5]:
# select multiple columns
df[['Name', 'Monthly_Salary']]

   Name  Monthly_Salary
0   ram           10000
1  ravi            3000
2    ak           40000
3    vj           50000
4    av             555
5    rj             777

In [6]:
# select single row || loc - label based index  // loc rows ko filter/select karta hai.
df.loc[df.Name=='ravi']

   Name  Age  Monthly_Salary
1  ravi   37            3000

In [7]:


# select multiple rows || loc - label based index
df.loc[(df.Name=='ram') & (df.Monthly_Salary>=9000)]

  Name  Age  Monthly_Salary
0  ram   26           10000

In [8]:
df.loc[0:2]

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000
2    ak   28           40000

In [9]:
# Select Rows || iloc - index-value based
# df.iloc[0]
df.iloc[0:2] # [start:stop:step]

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000

In [10]:

df.loc[0:2]  #0 2 include index
df.iloc[0:2]  #[start:stop:step]

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000

In [11]:

# 5 Filter Dataframe - Filtering by column values

In [12]:
df

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000
2    ak   28           40000
3    vj   19           50000
4    av    4             555
5    rj    3             777

In [13]:
df['Age'] >18

0     True
1     True
2     True
3     True
4    False
5    False
Name: Age, dtype: bool

In [14]:
df[df['Age']>=18]

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000
2    ak   28           40000
3    vj   19           50000

In [15]:
df_age_filter = df[df['Age'] >= 18] # filter and store dataframe in a new variable

In [16]:

df_age_filter

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000
2    ak   28           40000
3    vj   19           50000

In [17]:
df[(df['Age'] >= 28) & (df['Monthly_Salary'] >= 3000)] # multiple filter conditions

   Name  Age  Monthly_Salary
1  ravi   37            3000
2    ak   28           40000

In [18]:
df.where(df['Age'] >= 28) # where function replace values in a DataFrame based on a condition
# df[df['Age']>=28]

# Method	क्या करता है
# where()	condition false होने पर NaN डालता है
# loc[]	false rows को हटा देता है

# where() data cleaning और masking में बहुत use होता है।

   Name   Age  Monthly_Salary
0   NaN   NaN             NaN
1  ravi  37.0          3000.0
2    ak  28.0         40000.0
3   NaN   NaN             NaN
4   NaN   NaN             NaN
5   NaN   NaN             NaN

In [18]:
df.where(df['Age'] >= 28, other = 'Not Eligible')

           Name           Age Monthly_Salary
0  Not Eligible  Not Eligible   Not Eligible
1          ravi            37           3000
2            ak            28          40000
3  Not Eligible  Not Eligible   Not Eligible
4  Not Eligible  Not Eligible   Not Eligible
5  Not Eligible  Not Eligible   Not Eligible

In [19]:
# 6 Rows and Columns - Operation (Add, update, delete)

In [20]:
df

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000
2    ak   28           40000
3    vj   19           50000
4    av    4             555
5    rj    3             777

In [21]:
df.drop('DOJ2', axis=1, inplace=True)

KeyError: "['DOJ2'] not found in axis"

In [ ]:
df

In [22]:
# Create a new column
df['college'] = ['rjit', 'itm', 'mpct', 'mits','abc','vck']
df

   Name  Age  Monthly_Salary college
0   ram   26           10000    rjit
1  ravi   37            3000     itm
2    ak   28           40000    mpct
3    vj   19           50000    mits
4    av    4             555     abc
5    rj    3             777     vck

In [45]:
# Add new columns using existing column/s
df['Bonus'] = df['Salary'] * 0.20
df

   Name  Age  Salary college    Bonus
0   ram   26   90000    rjit  18000.0
1  ravi   37    3000     itm    600.0
2    ak   28   40000    mpct   8000.0
3    vj   19   50000    mits  10000.0
4    av    4     555     abc    111.0
5    rj    3     777     vck    155.4

In [23]:
# Add new row - at the end of dataframe
df.loc[len(df)] = ['viki', 23, 2000, 'mpct', 1000]
df

ValueError: cannot set a row with mismatched columns

In [47]:
# update value in dataframe using index-name
df.loc[0, 'Salary'] = 5000
df

   Name  Age  Salary college    Bonus
0   ram   26    5000    rjit  18000.0
1  ravi   37    3000     itm    600.0
2    ak   28   40000    mpct   8000.0
3    vj   19   50000    mits  10000.0
4    av    4     555     abc    111.0
5    rj    3     777     vck    155.4
6  viki   23    2000    mpct   1000.0

In [48]:
# update value in dataframe using column-value
df.loc[df.Name=='ram','Salary'] = 110000
df

   Name  Age  Salary college    Bonus
0   ram   26  110000    rjit  18000.0
1  ravi   37    3000     itm    600.0
2    ak   28   40000    mpct   8000.0
3    vj   19   50000    mits  10000.0
4    av    4     555     abc    111.0
5    rj    3     777     vck    155.4
6  viki   23    2000    mpct   1000.0

In [27]:
# delete value - rows and columns

In [49]:
# delete row using column-value filter
df = df.drop(df[df.Name == 'viki'].index) # delete row, axis= 0

In [50]:
df

   Name  Age  Salary college    Bonus
0   ram   26  110000    rjit  18000.0
1  ravi   37    3000     itm    600.0
2    ak   28   40000    mpct   8000.0
3    vj   19   50000    mits  10000.0
4    av    4     555     abc    111.0
5    rj    3     777     vck    155.4

In [51]:
# delete row using index-name filter
df.drop(1, axis=0)

  Name  Age  Salary college    Bonus
0  ram   26  110000    rjit  18000.0
2   ak   28   40000    mpct   8000.0
3   vj   19   50000    mits  10000.0
4   av    4     555     abc    111.0
5   rj    3     777     vck    155.4

In [52]:
df.drop('Bonus', axis=1, inplace=True) # delete one column
# df.drop(['Bonus', 'Team'], axis=1, inplace=True) # delete multiple columns

In [53]:
df

   Name  Age  Salary college
0   ram   26  110000    rjit
1  ravi   37    3000     itm
2    ak   28   40000    mpct
3    vj   19   50000    mits
4    av    4     555     abc
5    rj    3     777     vck

In [54]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace=True) # rename column name

In [55]:
df

   Name  Age  Monthly_Salary college
0   ram   26          110000    rjit
1  ravi   37            3000     itm
2    ak   28           40000    mpct
3    vj   19           50000    mits
4    av    4             555     abc
5    rj    3             777     vck

In [56]:
# sort values - order values in dataframe by asc or desc order
df.sort_values('Monthly_Salary') #ascending order, by default

   Name  Age  Monthly_Salary college
4    av    4             555     abc
5    rj    3             777     vck
1  ravi   37            3000     itm
2    ak   28           40000    mpct
3    vj   19           50000    mits
0   ram   26          110000    rjit

In [57]:
# sort values in descending order
df.sort_values('Monthly_Salary', ascending=False)

   Name  Age  Monthly_Salary college
0   ram   26          110000    rjit
3    vj   19           50000    mits
2    ak   28           40000    mpct
1  ravi   37            3000     itm
5    rj    3             777     vck
4    av    4             555     abc

In [24]:
# 7 working with date value

In [25]:
# create a date column - date of joining
df['DOJ2'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03','2024-04-03','2024-05-01']
df

   Name  Age  Monthly_Salary college        DOJ2
0   ram   26           10000    rjit  2024-01-01
1  ravi   37            3000     itm  2024-01-15
2    ak   28           40000    mpct  2024-03-28
3    vj   19           50000    mits  2024-03-03
4    av    4             555     abc  2024-04-03
5    rj    3             777     vck  2024-05-01

In [90]:
df.drop('DOJ23', axis=1, inplace=True) # delete one column

In [91]:
df

   Name  Age  Salary college        DOJ2
0   ram   26   90000    rjit  2024-01-01
1  ravi   37    3000     itm  2024-01-15
2    ak   28   40000    mpct  2024-03-28
3    vj   19   50000    mits  2024-03-03
4    av    4     555     abc  2024-04-03
5    rj    3     777     vck  2024-05-01

In [26]:
df['DOJ2'].dtype # object-type value
# dtype('O')

In [28]:
df['DOJ2'] = pd.to_datetime(df['DOJ2']) # change to date-time type

In [29]:
df['DOJ2'].dtype # date-time type

dtype('<M8[us]')

In [30]:
df1 = df

In [37]:
# creating a new column with incorrect date format
df1['DOJ23'] = ['01-01-2025', '15-01-2025', '28-03-2025', '03-03-2025','03-03-2025','03-03-2025']
df1

   Name  Age  Monthly_Salary college       DOJ2       DOJ23
0   ram   26           10000    rjit 2024-01-01  01-01-2025
1  ravi   37            3000     itm 2024-01-15  15-01-2025
2    ak   28           40000    mpct 2024-03-28  28-03-2025
3    vj   19           50000    mits 2024-03-03  03-03-2025
4    av    4             555     abc 2024-04-03  03-03-2025
5    rj    3             777     vck 2024-05-01  03-03-2025

In [38]:
df1['DOJ23'].dtype  # object-type value

In [39]:
df1['DOJ23'] = pd.to_datetime(df1['DOJ23'], format = '%d-%m-%Y') # change to date-time type using date-format

In [41]:
df1['DOJ23'].dtype

dtype('<M8[us]')

In [42]:
df1

   Name  Age  Monthly_Salary college       DOJ2      DOJ23
0   ram   26           10000    rjit 2024-01-01 2025-01-01
1  ravi   37            3000     itm 2024-01-15 2025-01-15
2    ak   28           40000    mpct 2024-03-28 2025-03-28
3    vj   19           50000    mits 2024-03-03 2025-03-03
4    av    4             555     abc 2024-04-03 2025-03-03
5    rj    3             777     vck 2024-05-01 2025-03-03

In [47]:
# extract year, month, week, day
df['DOJ2'].dt.year
# df['DOJ2'].dt.month
# df['DOJ2'].dt.day
# df['DOJ2'].dt.day_name()

0    2024
1    2024
2    2024
3    2024
4    2024
5    2024
Name: DOJ2, dtype: int32

In [48]:
# create new column using month extract function from DOJ2 column
df['Month'] = df['DOJ2'].dt.month

In [49]:
df

   Name  Age  Monthly_Salary college       DOJ2  Month
0   ram   26           10000    rjit 2024-01-01      1
1  ravi   37            3000     itm 2024-01-15      1
2    ak   28           40000    mpct 2024-03-28      3
3    vj   19           50000    mits 2024-03-03      3
4    av    4             555     abc 2024-04-03      4
5    rj    3             777     vck 2024-05-01      5

In [50]:
df['DOJ2'] + pd.Timedelta(days=90) # add 90 days to DOJ column

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
4   2024-07-02
5   2024-07-30
Name: DOJ2, dtype: datetime64[us]

In [65]:
# 8 Handling Missing Values

In [51]:
df

   Name  Age  Monthly_Salary college       DOJ2  Month
0   ram   26           10000    rjit 2024-01-01      1
1  ravi   37            3000     itm 2024-01-15      1
2    ak   28           40000    mpct 2024-03-28      3
3    vj   19           50000    mits 2024-03-03      3
4    av    4             555     abc 2024-04-03      4
5    rj    3             777     vck 2024-05-01      5

In [52]:
df.isnull() #  Detect missing values

    Name    Age  Monthly_Salary  college   DOJ2  Month
0  False  False           False    False  False  False
1  False  False           False    False  False  False
2  False  False           False    False  False  False
3  False  False           False    False  False  False
4  False  False           False    False  False  False
5  False  False           False    False  False  False

In [54]:
import numpy as np  # to create null values below

In [55]:
df.loc[df.Name=='ram', 'Monthly_Salary'] = np.nan # adding a null value

In [56]:
df

   Name  Age  Monthly_Salary college       DOJ2  Month
0   ram   26         10000.0    rjit 2024-01-01      1
1  ravi   37          3000.0     itm 2024-01-15      1
2    ak   28         40000.0    mpct 2024-03-28      3
3    vj   19         50000.0    mits 2024-03-03      3
4    av    4           555.0     abc 2024-04-03      4
5    rj    3             NaN     vck 2024-05-01      5

In [57]:
df.isnull()

    Name    Age  Monthly_Salary  college   DOJ2  Month
0  False  False           False    False  False  False
1  False  False           False    False  False  False
2  False  False           False    False  False  False
3  False  False           False    False  False  False
4  False  False           False    False  False  False
5  False  False            True    False  False  False

In [58]:
df.loc[df.Name=='ram', 'college'] = np.nan # adding a null value

In [59]:
df

   Name  Age  Monthly_Salary college       DOJ2  Month
0   ram   26         10000.0     NaN 2024-01-01      1
1  ravi   37          3000.0     itm 2024-01-15      1
2    ak   28         40000.0    mpct 2024-03-28      3
3    vj   19         50000.0    mits 2024-03-03      3
4    av    4           555.0     abc 2024-04-03      4
5    rj    3             NaN     vck 2024-05-01      5

In [60]:
df.isnull().sum() # count of null values by columns

Name              0
Age               0
Monthly_Salary    1
college           1
DOJ2              0
Month             0
dtype: int64

In [61]:
df.fillna(0) # fill null values with 0

   Name  Age  Monthly_Salary college       DOJ2  Month
0   ram   26         10000.0       0 2024-01-01      1
1  ravi   37          3000.0     itm 2024-01-15      1
2    ak   28         40000.0    mpct 2024-03-28      3
3    vj   19         50000.0    mits 2024-03-03      3
4    av    4           555.0     abc 2024-04-03      4
5    rj    3             0.0     vck 2024-05-01      5

In [64]:
df.loc[df.Name=='ram', 'Monthly_Salary'] = 30000
df.loc[df.Name.isin(['ram', 'rj']), 'Monthly_Salary'] = 20000

In [65]:
df

   Name  Age  Monthly_Salary college       DOJ2  Month
0   ram   26         20000.0     NaN 2024-01-01      1
1  ravi   37          3000.0     itm 2024-01-15      1
2    ak   28         40000.0    mpct 2024-03-28      3
3    vj   19         50000.0    mits 2024-03-03      3
4    av    4           555.0     abc 2024-04-03      4
5    rj    3         20000.0     vck 2024-05-01      5

In [66]:
df.fillna(0) # fill null values with 0

   Name  Age  Monthly_Salary college       DOJ2  Month
0   ram   26         20000.0       0 2024-01-01      1
1  ravi   37          3000.0     itm 2024-01-15      1
2    ak   28         40000.0    mpct 2024-03-28      3
3    vj   19         50000.0    mits 2024-03-03      3
4    av    4           555.0     abc 2024-04-03      4
5    rj    3         20000.0     vck 2024-05-01      5

In [135]:
df

   Name  Age   Salary college       DOJ2  Month
0   ram   26  30000.0    rjit 2024-01-01      1
1  ravi   37   3000.0     itm 2024-01-15      1
2    ak   28  40000.0    mpct 2024-03-28      3
3    vj   19  50000.0    mits 2024-03-03      3
4    av    4    555.0     abc 2024-04-03      4
5    rj    3      NaN     vck 2024-05-01      5