In [1]:
#2 Basic Dataframe Understanding

In [7]:
# import pandas
import pandas as pd

In [10]:
data = {
    'Name': ['ram', 'ravi', 'ak', 'vj',"av","rj"],
    'Age': [26,37,28,19,4,3],
    'Salary': [10000, 3000, 40000, 50000,555,777]
}

In [11]:
df = pd.DataFrame(data)
print(df)

   Name  Age  Salary
0   ram   26   10000
1  ravi   37    3000
2    ak   28   40000
3    vj   19   50000
4    av    4     555
5    rj    3     777

In [13]:
df.head(2) # top rows

   Name  Age  Salary
0   ram   26   10000
1  ravi   37    3000

In [14]:
df.tail(2) # last rows

  Name  Age  Salary
4   av    4     555
5   rj    3     777

In [15]:
df.shape # returns a tuple containing the shape of the DataFrame - rows & columns

(6, 3)

In [16]:
df.columns # list of column names in a dataframe

Index(['Name', 'Age', 'Salary'], dtype='str')

In [17]:
df.rename(columns={'Salary': 'Monthly_Salary1'}) # rename abhi dataframe mai change nai hua hai

   Name  Age  Monthly_Salary1
0   ram   26            10000
1  ravi   37             3000
2    ak   28            40000
3    vj   19            50000
4    av    4              555
5    rj    3              777

In [18]:
df #abhi dataframe mai change nai hua hai

   Name  Age  Salary
0   ram   26   10000
1  ravi   37    3000
2    ak   28   40000
3    vj   19   50000
4    av    4     555
5    rj    3     777

In [19]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace=True) # rename column name/s

In [20]:
df

   Name  Age  Monthly_Salary
0   ram   26           10000
1  ravi   37            3000
2    ak   28           40000
3    vj   19           50000
4    av    4             555
5    rj    3             777

In [21]:
df.info()  # info method prints information about the DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            6 non-null      str
 1   Age             6 non-null      int64
 2   Monthly_Salary  6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 276.0 bytes

In [17]:
df.describe() # describe method generates descriptive statistics of DataFrame,
#only for numerical-value columns

             Age  Monthly_Salary
count   4.000000        4.000000
mean   27.500000    25750.000000
std     7.416198    22779.742463
min    19.000000     3000.000000
25%    24.250000     8250.000000
50%    27.000000    25000.000000
75%    30.250000    42500.000000
max    37.000000    50000.000000

In [22]:
# save and load data from csv

In [23]:
df.to_csv('pn_data.csv')

In [24]:
df.to_csv('pn_data.csv', index=False) # save file - export data frame