In [1]:
# 📊 Project 2: Sales Analysis Report (Pandas)
# 🎯 Goal:

# Ek shop / company ke sales data se:

# Product wise sales
# Region wise revenue
# Best selling product
# Total profit analysis

In [1]:
import pandas as pd

In [2]:
data = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Laptop', 'Mouse', 'Keyboard', 'Laptop'],
    'Region': ['North', 'South', 'North', 'South', 'North', 'South', 'North'],
    'Sales': [50000, 500, 1500, 55000, 600, 1400, 60000],
    'Profit': [8000, 100, 300, 9000, 120, 280, 10000]
}

df = pd.DataFrame(data)
df

    Product Region  Sales  Profit
0    Laptop  North  50000    8000
1     Mouse  South    500     100
2  Keyboard  North   1500     300
3    Laptop  South  55000    9000
4     Mouse  North    600     120
5  Keyboard  South   1400     280
6    Laptop  North  60000   10000

In [6]:
# Product wise total sales
df.groupby('Product')['Sales'].sum()

Product
Keyboard      2900
Laptop      165000
Mouse         1100
Name: Sales, dtype: int64

In [7]:
# Product wise average profit
df.groupby('Product')['Profit'].mean()

Product
Keyboard     290.0
Laptop      9000.0
Mouse        110.0
Name: Profit, dtype: float64

In [9]:
# Region wise total sales
df.groupby('Region')['Sales'].sum()

Region
North    112100
South     56900
Name: Sales, dtype: int64

In [10]:
# Region wise profit
df.groupby('Region')['Profit'].sum()

Region
North    18420
South     9380
Name: Profit, dtype: int64

In [11]:
# Best selling product
df.groupby('Product')['Sales'].sum().sort_values(ascending=False)

Product
Laptop      165000
Keyboard      2900
Mouse         1100
Name: Sales, dtype: int64

In [3]:
# Full Business Report (MOST IMPORTANT)
report = df.groupby('Product').agg(
    total_sales=('Sales', 'sum'),
    avg_sales=('Sales', 'mean'),
    total_profit=('Profit', 'sum'),
    avg_profit=('Profit', 'mean')
)

report

          total_sales  avg_sales  total_profit  avg_profit
Product
Keyboard         2900     1450.0           580       290.0
Laptop         165000    55000.0         27000      9000.0
Mouse            1100      550.0           220       110.0

In [14]:
# Product	total_sales	total_profit
# Laptop	Highest	Highest
# Mouse	Low	Low
# Keyboard	Medium	Medium

In [15]:
# Top performing region
df.groupby('Region')['Sales'].sum().sort_values(ascending=False)

Region
North    112100
South     56900
Name: Sales, dtype: int64

In [ ]:
# GroupBy = category wise data split
# 👉 Aggregation = business insight nikalna